#!/usr/bin/env python3
"""
Regenerate src/runtime/func_registration.inc from the GENERATED recomp_out so
that seattle_register_func(addr, name) matches exactly what's defined there --
covering renamed funcs, recompiler-created static_0_* functions, and the
entrypoint. Run AFTER a regen (and BEFORE rename_overrides.py): registration
references the plain name (e.g. func_800D4C24), which rename_overrides leaves
pointing at the src/runtime override while the recomp body becomes *_original.

Entry address for each function is taken from its first `// 0xADDR:` comment,
so it is correct regardless of the (possibly renamed) symbol.
"""
import re
from pathlib import Path

ROOT = Path("D:/recomp/arcade/carnevil")
FUNCS = sorted((ROOT / "recomp_out/funcs").glob("funcs_*.c"))
OUT = ROOT / "src/runtime/func_registration.inc"

defn = re.compile(r'^RECOMP_FUNC void ([A-Za-z_]\w*)\(uint8_t\* rdram, recomp_context\* ctx\)')
addr_c = re.compile(r'//\s*0x([0-9A-Fa-f]+):')

regs = []          # (addr, name)
seen = set()
for fp in FUNCS:
    lines = fp.read_text(encoding="utf-8", errors="replace").split("\n")
    i = 0
    while i < len(lines):
        m = defn.match(lines[i])
        if m:
            name = m.group(1)
            # first instruction-address comment within the next ~6 lines
            addr = None
            for j in range(i+1, min(i+8, len(lines))):
                am = addr_c.search(lines[j])
                if am:
                    addr = int(am.group(1), 16)
                    break
            if addr is not None and addr not in seen:
                seen.add(addr)
                regs.append((addr, name))
        i += 1

regs.sort()
out = ["/* %d functions -- generated by tools/gen_func_registration.py from recomp_out */" % len(regs)]
out += ["seattle_register_func(0x%08X, %s);" % (a, n) for a, n in regs]
OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
print("Wrote %s with %d registrations" % (OUT.name, len(regs)))
