#!/usr/bin/env python3
"""
Regenerate src/runtime/func_registration.inc from carnevil_syms.toml so that
seattle_register_func(addr, name) always matches whatever names syms (and thus
the recompiled output) currently uses. Run this as part of the regen-adoption
workflow AFTER recompiling, so registration names stay consistent with the
renamed generated functions.

The entrypoint at the section's vram is registered as `recomp_entrypoint`
(MidwayRecomp's special name for it), matching the recompiler's output.

NOTE: do not run this against a stale recomp_out — it must be paired with a
regen that produced functions under the same names, or the build will fail to
link (registered name vs defined name mismatch).
"""
import re
from pathlib import Path

ROOT = Path("D:/recomp/arcade/carnevil")
SYMS = ROOT / "carnevil_syms.toml"
OUT = ROOT / "src/runtime/func_registration.inc"

text = SYMS.read_text(encoding="utf-8")

# Parse section vram (entrypoint) and all function name/vram pairs.
section_vram = None
m = re.search(r'^\s*vram = (0x[0-9A-Fa-f]+)\s*$', text, re.M)  # first vram = section
if m:
    section_vram = int(m.group(1), 16)

entries = []
name = None
for line in text.split("\n"):
    nm = re.match(r'^\s*name = "([^"]*)"\s*$', line)
    if nm:
        name = nm.group(1)
        continue
    vm = re.match(r'^\s*vram = (0x[0-9A-Fa-f]+)\s*$', line)
    if vm and name is not None:
        addr = int(vm.group(1), 16)
        entries.append((addr, name))
        name = None

# The very first (addr,name) is the section header's name/vram, skip it.
# Heuristic: section block has name like ".text"; drop entries whose name
# starts with '.'.
entries = [(a, n) for (a, n) in entries if not n.startswith(".")]

lines = ["/* %d functions -- generated by tools/gen_func_registration.py */" % len(entries)]
for addr, nm in entries:
    reg_name = "recomp_entrypoint" if (section_vram is not None and addr == section_vram) else nm
    lines.append("seattle_register_func(0x%08X, %s);" % (addr, reg_name))

OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("Wrote %s with %d registrations" % (OUT.name, len(entries)))
